### ISSUE TITLE
curl inside PHP container

### ISSUE THREAD

**Issue by m1kesk** [dambrogia/docker-testing#4]
Lets say you have 2 websites configured in apache

http://site1.docker:80
http://site2.docker:80

How can I do curl inside PHP container ?

$: curl http://site1.docker:80
$: curl: (6) Could not resolve host: site1.docker

curl localhost
(7) Failed to connect to localhost port 80: Connection refused

**Comment by dambrogia** [comment]
Hi @mikehudak, were you able to resolve this? What debugging steps have you tried? How are your virtual hosts set up? `Could not resolve host: site1.docker` sounds like you have some issues 
 finding your host. 

If you think about it -- in the repository setup, PHP doesn't think about apache. Apache only proxy's it's request through to the php-fpm service. So if you're curl'ing for localhost:80 in a php-fpm container, I wouldn't be expecting a response from a web service since there is no web service in php-fpm -- that is apache's job. Have you tried curling the apache container? It seems like that might be a better option.

**Comment by m1kesk** [comment]
I resolved this by adding `aliases` to docker-compose
